org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21

minecraft_version_range=[1.21.0,1.22)
neo_version=21.0.40-beta
neo_version_range=[21,)
loader_version_range=[4,)

mod_id=bluebirdlib
mod_name=BluebirdLib
mod_license=All-Rights-Reserved
mod_version=2.1
mod_group_id=it.bluebird
mod_authors=Bluebird Studios
mod_description=Common library for BluebirdStudio's mods
